### ISSUE TITLE
Bug: Not all pages displaying in ASM Select dropdown

### ISSUE THREAD

**Issue by jlahijani** [kongondo/MenuBuilder#21] opened 2015-04-24 18:14 UTC
Not sure how I can replicate this for you, but it seems some of the pages in my site are not shown in the ASM Select option dropdown.

If using the Page Auto Complete option, it finds them however.

**Comment by kongondo** [comment] 2015-04-30 20:27
This behaviour is not a bug. Similar to the limit set by ProcessWire's Page Autocomplete and in other places, for performance reasons, by default ASM Select in MenuBuilder is limited to returning a maximum of 50 results. However, you are not tied to using this. When editing your menu, look under the **Main** tab, just after the **Menu Title**, there is an option **Pages selectable in menu** in which you can specify a valid ProcessWire selector to return the number and/or types (e.g. based on a certain template) of pages you want shown in your ASM Select dropdown. Note that you can only see that setting if you are logged in as a SuperAdmin or have the [permission](https://github.com/kongondo/MenuBuilder#permissions) **menu-builder-selectable**. In your case, all you would need to enter there is **limit=XX**.

**Comment by kongondo** [comment] 2016-01-16 18:40
Closing issue. Admin/User with permission 'menu-builder-selectable' can add 'limit=n' in the option 'Pages selectable in menu' under the tab 'Main'. The default '50 pages' limit will then be overridden. Note, **you don't** have to add template!=admin in your selector. That's taken care of by the module.

**Closed by kongondo** 2016-01-16 18:40 UTC
